#include "mlg.h"

PWNAGE BEGINS
    IF ILLUMINATI CONFIRMED M8
        SHOUT THE 1 ST OF MEMES M9 RITE NOOB
    SHREKT
    MEME HAX LOLHAX IS QUICKSCOPE MEME YOLO 5 SWAG LOL
    MTN MEME LEGITNESS IS 1 ST DEW LEGITNESS LESS 6 TH DORITOS WIN LEGITNESS M8
        THE LEGITNESS OF LOLHAX M9 IS LEGITNESS LOL
        COUNT THE LEGITNESS OF LOLHAX M9 RITE SKRUB
    SHREKT
    NOSCOPE YOLO SWAG LOLHAX NOOB
	GET REKT LOL
SHREKT
